name: "dealenx"
description: "Блог о разработке, AI и инструментах"
language: ru

discussions: https://github.com/dealenx/dealenx/discussions/categories/announcements
telegram: https://t.me/dealenxdev